### PR TITLE
Raise 404 instead of 400 when project not found in db

### LINKED ISSUE #100: Status code for project not found
Hello! Not sure whether this is the right place to raise this issue... But I noticed that when attempting to make a request for a project that doesn't exist, the response code is 400 (Bad request). To me, it would be more appropriate to respond with a 404 (Resource not found).

Context: I am working on better error handling for this case in the UI.

### PR DESCRIPTION
**Pull request by Dinika**
fixes #100

### CODE REVIEW

**Review by xari — APPROVED** [review]
Looks good. Thanks @Dinika . 

I haven't checked yet whether the same would also apply to the Virtual Lab response status in the event of a VL not being found. Perhaps there will also be a change to be made there as well.

In any case; thanks!

**Comment by Dinika** [comment]
> I haven't checked yet whether the same would also apply to the Virtual Lab response status in the event of a VL not being found. Perhaps there will also be a change to be made there as well.


I did check this already. Virtual labs routes [already return 404](https://github.com/BlueBrain/virtual-lab-api/blob/main/virtual_labs/core/authorization/verify_vlab_read.py#L49) if lab not found.

**Comment by bilalesi** [comment]
`sqlalchemy` error can be anything why we return not found ? are we sure that we always be the object not found in db

**Comment by Dinika** [comment]
> `sqlalchemy` error can be anything why we return not found ? are we sure that we always be the object not found in db

Fair point. I've changed the code now. In case of `NoResultFound` sql exception, we will raise 404 as requested by @xari. The only other errors that can happen in this step (when we are trying to fetch a lab/project from db) would happen when things are really wrong with the db (like the db is down or inconsistent). In those cases I raise 500.

**Review by bilalesi — APPROVED** [review]

**Pull request merged**
